# .forgejo/workflows/demo.yaml
name: Demo
run-name: ${{ github.actor }} is testing
on: [push]
jobs:
  Explore-CI:
    runs-on: flakes-action
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: run elixir code
        run: |
          elixir --eval "IO.puts(\"hello\")"
      - run: echo "This job's status is ${{ job.status }}."

  upload-one:
    runs-on: flakes-action
    steps:
    - run: mkdir -p path/

    - run: echo hello > path/world.txt

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: path/world.txt
